import type { Metadata } from "next";
import "./globals.css";
import { metaData } from "@/typeScript/metaData";
import {Roboto} from "next/font/google"
import { Toaster } from "sonner";
import StoreProvider from "./StoreProvider";

const roboto=Roboto({subsets:['latin'],weight:"400"})

export const metadata: Metadata = {
  title: metaData.title,
  description: "Generated by create next app",
};

export default   function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased`}
      >
        <Toaster position="top-center"/>
              <StoreProvider>
              {children}
              </StoreProvider>
          
        
      </body>
    </html>
  );
}
